# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(855, 700)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.imageLabel = QtGui.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(140, 50, 601, 401))
        self.imageLabel.setObjectName(_fromUtf8("imageLabel"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 580, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 580, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 580, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 580, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(600, 580, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(730, 580, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.btn_la_muse = QtGui.QPushButton(self.centralwidget)
        self.btn_la_muse.setGeometry(QtCore.QRect(60, 490, 81, 81))
        self.btn_la_muse.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/la_muse.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_la_muse.setIcon(icon)
        self.btn_la_muse.setIconSize(QtCore.QSize(80, 80))
        self.btn_la_muse.setObjectName(_fromUtf8("btn_la_muse"))
        self.btn_rain_princess = QtGui.QPushButton(self.centralwidget)
        self.btn_rain_princess.setGeometry(QtCore.QRect(190, 490, 81, 81))
        self.btn_rain_princess.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/rain_princess.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rain_princess.setIcon(icon1)
        self.btn_rain_princess.setIconSize(QtCore.QSize(80, 80))
        self.btn_rain_princess.setObjectName(_fromUtf8("btn_rain_princess"))
        self.btn_scream = QtGui.QPushButton(self.centralwidget)
        self.btn_scream.setGeometry(QtCore.QRect(320, 490, 81, 81))
        self.btn_scream.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/scream.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_scream.setIcon(icon2)
        self.btn_scream.setIconSize(QtCore.QSize(80, 80))
        self.btn_scream.setObjectName(_fromUtf8("btn_scream"))
        self.btn_udnie = QtGui.QPushButton(self.centralwidget)
        self.btn_udnie.setGeometry(QtCore.QRect(450, 490, 81, 81))
        self.btn_udnie.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("images/udnie.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_udnie.setIcon(icon3)
        self.btn_udnie.setIconSize(QtCore.QSize(80, 80))
        self.btn_udnie.setCheckable(False)
        self.btn_udnie.setAutoDefault(False)
        self.btn_udnie.setObjectName(_fromUtf8("btn_udnie"))
        self.btn_wave = QtGui.QPushButton(self.centralwidget)
        self.btn_wave.setGeometry(QtCore.QRect(580, 490, 81, 81))
        self.btn_wave.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("images/wave.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wave.setIcon(icon4)
        self.btn_wave.setIconSize(QtCore.QSize(80, 80))
        self.btn_wave.setObjectName(_fromUtf8("btn_wave"))
        self.btn_wreck = QtGui.QPushButton(self.centralwidget)
        self.btn_wreck.setGeometry(QtCore.QRect(710, 490, 81, 81))
        self.btn_wreck.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("images/wreck.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wreck.setIcon(icon5)
        self.btn_wreck.setIconSize(QtCore.QSize(80, 80))
        self.btn_wreck.setObjectName(_fromUtf8("btn_wreck"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menustyle = QtGui.QMenu(self.menubar)
        self.menustyle.setObjectName(_fromUtf8("menustyle"))
        self.menuhelp = QtGui.QMenu(self.menubar)
        self.menuhelp.setObjectName(_fromUtf8("menuhelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_File = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("resources/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_File.setIcon(icon6)
        self.actionNew_File.setObjectName(_fromUtf8("actionNew_File"))
        self.actionOpen_File = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("resources/fileopen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_File.setIcon(icon7)
        self.actionOpen_File.setObjectName(_fromUtf8("actionOpen_File"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("resources/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon8)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("resources/filesaveas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon9)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionPrint = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("resources/fileprint.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon10)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("resources/filequit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon11)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionla_muse = QtGui.QAction(MainWindow)
        self.actionla_muse.setObjectName(_fromUtf8("actionla_muse"))
        self.actionrain_princess = QtGui.QAction(MainWindow)
        self.actionrain_princess.setObjectName(_fromUtf8("actionrain_princess"))
        self.actionscream = QtGui.QAction(MainWindow)
        self.actionscream.setObjectName(_fromUtf8("actionscream"))
        self.actionudine = QtGui.QAction(MainWindow)
        self.actionudine.setObjectName(_fromUtf8("actionudine"))
        self.actionwave = QtGui.QAction(MainWindow)
        self.actionwave.setObjectName(_fromUtf8("actionwave"))
        self.actionwreck = QtGui.QAction(MainWindow)
        self.actionwreck.setObjectName(_fromUtf8("actionwreck"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.action_Help_F1 = QtGui.QAction(MainWindow)
        self.action_Help_F1.setObjectName(_fromUtf8("action_Help_F1"))
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menustyle.addAction(self.actionla_muse)
        self.menustyle.addAction(self.actionrain_princess)
        self.menustyle.addAction(self.actionscream)
        self.menustyle.addAction(self.actionudine)
        self.menustyle.addAction(self.actionwave)
        self.menustyle.addAction(self.actionwreck)
        self.menuhelp.addAction(self.action_About)
        self.menuhelp.addAction(self.action_Help_F1)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menustyle.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())
        self.toolBar.addAction(self.actionOpen_File)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.imageLabel.setText(_translate("MainWindow", "0", None))
        self.label.setText(_translate("MainWindow", "la_muse", None))
        self.label_2.setText(_translate("MainWindow", "rain_princess", None))
        self.label_3.setText(_translate("MainWindow", "scream", None))
        self.label_4.setText(_translate("MainWindow", "udnie", None))
        self.label_5.setText(_translate("MainWindow", "wave", None))
        self.label_6.setText(_translate("MainWindow", "wreck", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menustyle.setTitle(_translate("MainWindow", "&Style", None))
        self.menuhelp.setTitle(_translate("MainWindow", "&Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionNew_File.setText(_translate("MainWindow", "&New", None))
        self.actionNew_File.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionOpen_File.setText(_translate("MainWindow", "&Open", None))
        self.actionOpen_File.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save &As", None))
        self.actionPrint.setText(_translate("MainWindow", "&Print", None))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionla_muse.setText(_translate("MainWindow", "la_muse", None))
        self.actionrain_princess.setText(_translate("MainWindow", "rain_princess", None))
        self.actionscream.setText(_translate("MainWindow", "scream", None))
        self.actionudine.setText(_translate("MainWindow", "udnie", None))
        self.actionwave.setText(_translate("MainWindow", "wave", None))
        self.actionwreck.setText(_translate("MainWindow", "wreck", None))
        self.action_About.setText(_translate("MainWindow", "&About", None))
        self.action_Help_F1.setText(_translate("MainWindow", "&Help                     F1", None))

